import type { Metadata } from "next";
import { Rajdhani, IBM_Plex_Mono } from "next/font/google";

import { CopilotKit } from "@copilotkit/react-core";
import "./globals.css";
import "@copilotkit/react-ui/styles.css";

const rajdhani = Rajdhani({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-rajdhani",
});

const ibmPlexMono = IBM_Plex_Mono({
  weight: ["300", "400", "500", "600"],
  subsets: ["latin"],
  variable: "--font-ibm-plex-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${rajdhani.variable} ${ibmPlexMono.variable} antialiased`}>
        <CopilotKit runtimeUrl="/api/copilotkit"
                    agent="strands_agent"
                    enableInspector={false}> {/* enable inspector to see the events including tool calls*/}
          {children}
        </CopilotKit>
      </body>
    </html>
  );
}
